import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import BootstrapClient from "./Components/BootstrapClient";
import { Nav } from "./Components/Nav";
import Menu from "./Menu/page";
import Nav2 from "./Components/Nav2";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Nav2 />
      {children}
      <BootstrapClient />
      </body>
    </html>
  );
}
